"""Streamlit clinical-ops dashboard.

Three pages mirror the Power BI report:

1. Hospital Operations - encounter volume, LOS, readmission, ED throughput.
2. Revenue & Claims     - claim mix, denial rate, $ leakage.
3. Live Vital Signs     - last-24h vitals, anomaly drilldown.

Data source: Synapse `dw` schema via pyodbc. For local development without
Synapse, set `HCDW_DEMO_MODE=1` to load the bundled `demo_data/` Parquet
files (generated by `dashboards/streamlit/build_demo_data.py`).

Run locally:
    streamlit run dashboards/streamlit/app.py
"""
from __future__ import annotations

import os
from pathlib import Path

import pandas as pd
import plotly.express as px
import streamlit as st

DEMO_DIR = Path(__file__).resolve().parent / "demo_data"
DEMO_MODE = os.environ.get("HCDW_DEMO_MODE", "0") == "1" or not DEMO_DIR.exists() is False

st.set_page_config(
    page_title="Healthcare DW - Clinical Operations",
    page_icon="🩺",
    layout="wide",
    initial_sidebar_state="expanded",
)


# ---------------------------------------------------------------------------
#   Data access
# ---------------------------------------------------------------------------
@st.cache_resource(show_spinner=False)
def _connect():
    """Synapse connection. Cached at app level."""
    if os.environ.get("HCDW_DEMO_MODE", "0") == "1":
        return None
    try:
        import pyodbc
    except ImportError:
        return None
    server = os.environ.get("SYNAPSE_SERVER")
    db = os.environ.get("SYNAPSE_DATABASE")
    user = os.environ.get("SYNAPSE_USER")
    pwd = os.environ.get("SYNAPSE_PASSWORD")
    if not all([server, db, user, pwd]):
        return None
    return pyodbc.connect(
        f"DRIVER={{ODBC Driver 18 for SQL Server}};SERVER={server};DATABASE={db};"
        f"UID={user};PWD={pwd};Encrypt=Yes;TrustServerCertificate=No",
        autocommit=True,
    )


@st.cache_data(ttl=300, show_spinner=False)
def _query(sql: str, params: tuple = ()) -> pd.DataFrame:
    conn = _connect()
    if conn is not None:
        return pd.read_sql(sql, conn, params=params)
    # Demo fallback
    table = sql.split("FROM")[1].split()[0].strip("[]").split(".")[-1]
    f = DEMO_DIR / f"{table}.parquet"
    if not f.exists():
        st.warning(f"Demo dataset {f.name} not found; run build_demo_data.py.")
        return pd.DataFrame()
    return pd.read_parquet(f)


def _kpi(label: str, value, help_text: str | None = None, delta=None) -> None:
    st.metric(label, value, delta=delta, help=help_text)


# ---------------------------------------------------------------------------
#   Sidebar filters
# ---------------------------------------------------------------------------
st.sidebar.title("Filters")
hospitals_df = _query("SELECT DISTINCT hospital_name FROM dw.vw_encounter_enriched ORDER BY hospital_name")
hospitals = ["All"] + (hospitals_df["hospital_name"].tolist() if not hospitals_df.empty else [])
selected_hospital = st.sidebar.selectbox("Hospital", hospitals, index=0)

date_range = st.sidebar.date_input(
    "Date range",
    value=(pd.Timestamp.utcnow() - pd.Timedelta(days=90), pd.Timestamp.utcnow()),
)
if isinstance(date_range, tuple) and len(date_range) == 2:
    from_date, to_date = date_range
else:
    from_date = pd.Timestamp.utcnow() - pd.Timedelta(days=90)
    to_date = pd.Timestamp.utcnow()

st.sidebar.caption(
    "Connected to Synapse" if _connect() is not None else "Demo mode (local Parquet)"
)


# ---------------------------------------------------------------------------
#   Pages
# ---------------------------------------------------------------------------
PAGES = ["Hospital Operations", "Revenue & Claims", "Live Vital Signs"]
page = st.sidebar.radio("Page", PAGES)


def _filter_clause() -> str:
    bits = []
    if selected_hospital != "All":
        bits.append(f"hospital_name = '{selected_hospital}'")
    bits.append(f"encounter_date BETWEEN '{from_date}' AND '{to_date}'")
    return " AND ".join(bits)


def page_operations() -> None:
    st.title("Hospital Operations")
    st.caption(f"Window: {from_date} -> {to_date}.  Hospital: {selected_hospital}")

    where = _filter_clause()
    enc = _query(f"SELECT * FROM dw.vw_encounter_enriched WHERE {where}")

    if enc.empty:
        st.info("No encounters in the selected window.")
        return

    c1, c2, c3, c4 = st.columns(4)
    with c1:
        _kpi("Encounters", f"{len(enc):,}", "Total encounters in window.")
    with c2:
        ip = enc[enc["is_inpatient"] == True]
        _kpi(
            "Avg LOS (inpatient)",
            f"{ip['length_of_stay_hours'].mean():.1f} h" if not ip.empty else "—",
        )
    with c3:
        readmit = (enc["is_readmission_30d"] == True).sum()
        denom = (enc["is_inpatient"] == True).sum()
        _kpi(
            "30d readmission %",
            f"{(readmit / denom * 100):.2f}%" if denom else "—",
        )
    with c4:
        _kpi(
            "ED visits",
            f"{(enc['encounter_class'] == 'emergency').sum():,}",
        )

    left, right = st.columns(2)
    with left:
        st.subheader("Encounter mix by class")
        mix = enc["encounter_class"].value_counts().reset_index()
        mix.columns = ["encounter_class", "count"]
        fig = px.bar(mix, x="encounter_class", y="count", color="encounter_class")
        fig.update_layout(showlegend=False, height=350)
        st.plotly_chart(fig, use_container_width=True)
    with right:
        st.subheader("Encounters per day")
        ts = enc.groupby("encounter_date").size().reset_index(name="encounters")
        fig = px.line(ts, x="encounter_date", y="encounters")
        fig.update_layout(height=350)
        st.plotly_chart(fig, use_container_width=True)

    st.subheader("Top 10 diagnoses")
    top_dx = (
        enc.dropna(subset=["primary_diagnosis"])
           .groupby(["primary_icd10_code", "primary_diagnosis"])
           .size().reset_index(name="count")
           .sort_values("count", ascending=False)
           .head(10)
    )
    st.dataframe(top_dx, use_container_width=True, hide_index=True)


def page_revenue() -> None:
    st.title("Revenue & Claims")

    where = " AND ".join([
        f"service_date BETWEEN '{from_date}' AND '{to_date}'",
        f"hospital_name = '{selected_hospital}'" if selected_hospital != "All" else "1=1",
    ])
    claims = _query(f"SELECT * FROM dw.vw_claim_enriched WHERE {where}")
    if claims.empty:
        st.info("No claims in the selected window.")
        return

    c1, c2, c3, c4 = st.columns(4)
    with c1:
        _kpi("Total claims", f"{len(claims):,}")
    with c2:
        _kpi("Total billed", f"{claims['billed_amount'].sum():,.0f}")
    with c3:
        _kpi(
            "Denial rate",
            f"{(claims['is_denied'].sum() / len(claims) * 100):.2f}%",
        )
    with c4:
        billed = claims["billed_amount"].sum()
        paid = claims["paid_amount"].sum()
        _kpi(
            "Collection rate",
            f"{(paid / billed * 100):.1f}%" if billed else "—",
            help_text="paid / billed",
        )

    left, right = st.columns(2)
    with left:
        st.subheader("Status mix")
        mix = claims["status"].value_counts().reset_index()
        mix.columns = ["status", "count"]
        fig = px.pie(mix, names="status", values="count", hole=0.45)
        fig.update_layout(height=350)
        st.plotly_chart(fig, use_container_width=True)
    with right:
        st.subheader("Denial rate by payer")
        per_payer = (
            claims.groupby("payer_name")
                  .agg(claims=("claim_sk", "count"),
                       denied=("is_denied", "sum"))
                  .assign(denial_pct=lambda d: 100 * d["denied"] / d["claims"])
                  .reset_index()
                  .sort_values("denial_pct", ascending=False)
        )
        fig = px.bar(per_payer, x="payer_name", y="denial_pct",
                     hover_data=["claims", "denied"])
        fig.update_layout(height=350, yaxis_title="denial %")
        st.plotly_chart(fig, use_container_width=True)

    st.subheader("Monthly billed vs paid")
    monthly = (
        claims.assign(month=pd.to_datetime(claims["service_date"]).dt.to_period("M").astype(str))
              .groupby("month")[["billed_amount", "paid_amount"]].sum()
              .reset_index()
    )
    fig = px.bar(monthly, x="month", y=["billed_amount", "paid_amount"], barmode="group")
    st.plotly_chart(fig, use_container_width=True)


def page_vitals() -> None:
    st.title("Live Vital Signs")
    st.caption("Last 24 hours.  Auto-refresh every 60s when connected to Synapse.")

    if _connect() is not None:
        st_autorefresh = None
        try:
            from streamlit_autorefresh import st_autorefresh as _ar  # noqa: WPS433
            st_autorefresh = _ar
        except ImportError:
            pass
        if st_autorefresh:
            st_autorefresh(interval=60_000, key="vital_refresh")

    sql = """
        SELECT TOP (500) *
        FROM dw.vw_vital_signs_minute
        WHERE minute_start_utc >= DATEADD(HOUR, -24, SYSUTCDATETIME())
        ORDER BY minute_start_utc DESC
    """
    vs = _query(sql)
    if vs.empty:
        st.info("No vital sign data in the last 24h.")
        return

    c1, c2, c3 = st.columns(3)
    with c1:
        _kpi("Devices reporting", vs["device_id"].nunique())
    with c2:
        _kpi("Anomaly minutes", int((vs["anomaly_event_count"] > 0).sum()))
    with c3:
        active_alerts = vs[vs["anomaly_event_count"] > 0].head(20)
        _kpi("Alerts (last 20)", len(active_alerts))

    st.subheader("Active alerts")
    alerts = (
        vs[vs["anomaly_event_count"] > 0]
            .head(20)[[
                "minute_start_utc", "patient_name", "hospital_name",
                "primary_anomaly_kind", "heart_rate_avg", "spo2_min",
                "systolic_avg", "temperature_c_max",
            ]]
    )
    st.dataframe(alerts, use_container_width=True, hide_index=True)

    pick = st.selectbox(
        "Drill-down patient",
        sorted(vs["patient_name"].dropna().unique().tolist()),
    )
    sub = vs[vs["patient_name"] == pick].sort_values("minute_start_utc")
    if not sub.empty:
        fig = px.line(
            sub, x="minute_start_utc",
            y=["heart_rate_avg", "spo2_avg", "systolic_avg"],
            title=f"{pick} - last 24h",
        )
        st.plotly_chart(fig, use_container_width=True)


PAGE_FUNCS = {
    "Hospital Operations": page_operations,
    "Revenue & Claims": page_revenue,
    "Live Vital Signs": page_vitals,
}
PAGE_FUNCS[page]()
